Repository ghis22130/sidedish, pull requests merged in 2021-04, with the labels that each got.

#11 feat: Connect database
  BE/build.gradle
  BE/src/main/resources/application.properties
Labels: BE, enhancement

#14 [BE] Model 설계
  BE/src/main/java/com/team10/banchan/model/Badge.java
  BE/src/main/java/com/team10/banchan/model/Category.java
  BE/src/main/java/com/team10/banchan/model/DeliveryDay.java
  BE/src/main/java/com/team10/banchan/model/DeliveryType.java
  BE/src/main/java/com/team10/banchan/model/DetailSection.java
  BE/src/main/java/com/team10/banchan/model/Item.java
  BE/src/main/java/com/team10/banchan/model/Section.java
  BE/src/main/java/com/team10/banchan/model/ThumbImage.java
  BE/src/main/java/com/team10/banchan/repository/CategoryRepository.java
  BE/src/main/java/com/team10/banchan/repository/ItemRepository.java
  BE/src/main/java/com/team10/banchan/repository/SectionRepository.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/team10/banchan/repository/ItemRepositoryTest.java
  BE/src/test/java/com/team10/banchan/repository/SectionRepositoryTest.java
  BE/src/test/resources/application.properties
  BE/src/test/resources/data.sql
Labels: BE, enhancement

#18 [BE] DTO 설계
  BE/src/main/java/com/team10/banchan/dto/ItemDetail.java
  BE/src/main/java/com/team10/banchan/dto/ItemDetailResponse.java
  BE/src/main/java/com/team10/banchan/dto/ItemSummary.java
  BE/src/main/java/com/team10/banchan/model/Badge.java
  BE/src/main/java/com/team10/banchan/model/Category.java
  BE/src/main/java/com/team10/banchan/model/DeliveryDay.java
  BE/src/main/java/com/team10/banchan/model/DeliveryType.java
  BE/src/main/java/com/team10/banchan/model/Description.java
  BE/src/main/java/com/team10/banchan/model/DetailSection.java
  BE/src/main/java/com/team10/banchan/model/Item.java
  BE/src/main/java/com/team10/banchan/model/Prices.java
  BE/src/main/java/com/team10/banchan/model/Section.java
  BE/src/main/java/com/team10/banchan/model/ThumbImage.java
  BE/src/main/java/com/team10/banchan/model/TopImage.java
  BE/src/test/java/com/team10/banchan/model/PricesTest.java
  BE/src/test/java/com/team10/banchan/repository/ItemRepositoryTest.java
  BE/src/test/java/com/team10/banchan/repository/SectionRepositoryTest.java
Labels: BE, enhancement

#19 [BE] Service 구현
  BE/src/main/java/com/team10/banchan/dto/ItemDetail.java
  BE/src/main/java/com/team10/banchan/exception/NotFoundException.java
  BE/src/main/java/com/team10/banchan/model/Item.java
  BE/src/main/java/com/team10/banchan/repository/ItemRepository.java
  BE/src/main/java/com/team10/banchan/repository/SectionRepository.java
  BE/src/main/java/com/team10/banchan/service/ItemDetailService.java
  BE/src/main/java/com/team10/banchan/service/SectionService.java
Labels: BE, enhancement

#22 [BE] Controller 구현
  BE/src/main/java/com/team10/banchan/controller/ItemDetailController.java
  BE/src/main/java/com/team10/banchan/controller/SectionController.java
  BE/src/main/java/com/team10/banchan/dto/ItemDetail.java
  BE/src/main/java/com/team10/banchan/model/Badge.java
  BE/src/main/java/com/team10/banchan/model/DeliveryDay.java
  BE/src/main/java/com/team10/banchan/model/DeliveryType.java
  BE/src/main/java/com/team10/banchan/model/Item.java
  BE/src/main/java/com/team10/banchan/response/ResponseBody.java
Labels: BE, enhancement

#28 [BE] 서버배포
  BE/src/main/java/com/team10/banchan/dto/ItemDetail.java
  BE/src/main/java/com/team10/banchan/model/Item.java
  BE/src/main/java/com/team10/banchan/model/ItemImages.java
  BE/src/main/java/com/team10/banchan/model/Prices.java
  BE/src/main/java/com/team10/banchan/model/TopImage.java
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/team10/banchan/repository/ItemRepositoryTest.java
  BE/src/test/resources/data.sql
Labels: BE, deploy, enhancement

#29 [BE] Deploy
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/team10/banchan/BanchanApplication.java
  BE/src/main/java/com/team10/banchan/controller/ItemDetailController.java
  BE/src/main/java/com/team10/banchan/controller/SectionController.java
  BE/src/main/java/com/team10/banchan/dto/ItemDetail.java
  BE/src/main/java/com/team10/banchan/dto/ItemDetailResponse.java
  BE/src/main/java/com/team10/banchan/dto/ItemSummary.java
  BE/src/main/java/com/team10/banchan/exception/NotFoundException.java
  BE/src/main/java/com/team10/banchan/model/Badge.java
  BE/src/main/java/com/team10/banchan/model/Category.java
  BE/src/main/java/com/team10/banchan/model/DeliveryDay.java
  BE/src/main/java/com/team10/banchan/model/DeliveryType.java
  BE/src/main/java/com/team10/banchan/model/Description.java
  BE/src/main/java/com/team10/banchan/model/DetailSection.java
  BE/src/main/java/com/team10/banchan/model/Item.java
  BE/src/main/java/com/team10/banchan/model/ItemImages.java
  BE/src/main/java/com/team10/banchan/model/Prices.java
  BE/src/main/java/com/team10/banchan/model/Section.java
  BE/src/main/java/com/team10/banchan/model/ThumbImage.java
  BE/src/main/java/com/team10/banchan/repository/CategoryRepository.java
  BE/src/main/java/com/team10/banchan/repository/ItemRepository.java
  BE/src/main/java/com/team10/banchan/repository/SectionRepository.java
  BE/src/main/java/com/team10/banchan/response/ResponseBody.java
  BE/src/main/java/com/team10/banchan/service/ItemDetailService.java
  BE/src/main/java/com/team10/banchan/service/SectionService.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/team10/banchan/BanchanApplicationTests.java
  BE/src/test/java/com/team10/banchan/model/PricesTest.java
  BE/src/test/java/com/team10/banchan/repository/ItemRepositoryTest.java
  BE/src/test/java/com/team10/banchan/repository/SectionRepositoryTest.java
  BE/src/test/resources/application.properties
  BE/src/test/resources/data.sql
Labels: deploy

#30 [BE] 데이터 수정
  BE/src/main/java/com/team10/banchan/dto/ItemDetail.java
  BE/src/main/java/com/team10/banchan/dto/ItemSummary.java
Labels: BE, enhancement

#33 [BE] fix: Edit @RequestMapping
  BE/src/main/java/com/team10/banchan/controller/SectionController.java
Labels: BE, bug

#35 [BE] Order 기능 구현
  BE/src/main/java/com/team10/banchan/controller/ItemDetailController.java
  BE/src/main/java/com/team10/banchan/dto/OrderInfo.java
  BE/src/main/java/com/team10/banchan/dto/OrderRequest.java
  BE/src/main/java/com/team10/banchan/dto/OutOfOrderInfo.java
  BE/src/main/java/com/team10/banchan/exception/OutOfStockException.java
  BE/src/main/java/com/team10/banchan/exceptionhandler/GlobalExceptionHandler.java
  BE/src/main/java/com/team10/banchan/model/Item.java
  BE/src/main/java/com/team10/banchan/model/Order.java
  BE/src/main/java/com/team10/banchan/model/Prices.java
  BE/src/main/java/com/team10/banchan/repository/OrderRepository.java
  BE/src/main/java/com/team10/banchan/service/ItemDetailService.java
  BE/src/main/resources/schema.sql
Labels: BE, enhancement

#36 [BE] 주문하기 기능 구현 & 예외처리
  BE/src/main/java/com/team10/banchan/controller/ItemDetailController.java
  BE/src/main/java/com/team10/banchan/dto/ItemDetail.java
  BE/src/main/java/com/team10/banchan/dto/ItemSummary.java
  BE/src/main/java/com/team10/banchan/dto/OrderInfo.java
  BE/src/main/java/com/team10/banchan/dto/OrderRequest.java
  BE/src/main/java/com/team10/banchan/dto/OutOfOrderInfo.java
  BE/src/main/java/com/team10/banchan/exception/OutOfStockException.java
  BE/src/main/java/com/team10/banchan/exceptionhandler/GlobalExceptionHandler.java
  BE/src/main/java/com/team10/banchan/model/Item.java
  BE/src/main/java/com/team10/banchan/response/ResponseBody.java
  BE/src/main/java/com/team10/banchan/service/ItemDetailService.java
Labels: BE, enhancement
